# Generated by Django 5.1.2 on 2024-11-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
